### PR TITLE
Reorganize platformio.ini, add SPIFFS/LittleFS support

### LINKED ISSUE #26: Remove deprecated SPIFFS package
`warning: 'SPIFFS' is deprecated: SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems.`

### PR DESCRIPTION
**Pull request by floatplane**
This resolves #26 and adds support for choosing LittleFS/SPIFFS at compile time (controlled by the compiler flag `USE_SPIFFS`). Note that compiling ESPAsyncWebServer will still throw warnings about references to SPIFFS, but the offending code is never called.

We produce separate artifacts for each board:
image

### CODE REVIEW

**Comment by floatplane** [comment]
@Allram I am going to hold off on merging this for a couple of days - I had a spare WEMOS board that I was using for testing, but now I can't find it. Ordered a few more, along with some ESP32 boards for good measure.

**Comment by Allram** [comment]
I went on vacation. But i got some Wemos board with me (😂), so i will see if i can do some tests tonight.

**Comment by floatplane** [comment]
Noooooo relax and enjoy your vacation! 🌴 🍹 🌞

**Comment by floatplane** [comment]
Seems to be working as intended on ESP32 - ran through initial install and OTA update scenarios for both SPIFFS and LittleFS. Plumbed the firmware name through as a preprocessor define, so now it shows up in a couple of places:

hover text in footer | on status page
--- | ---
image | image

Still need to run through tests on the WEMOS board but I don't really foresee any issues at this point...

**Comment by floatplane** [comment]
> Still need to run through tests on the WEMOS board but I don't really foresee any issues at this point...

lol this assumption was totally incorrect! so glad I tested this case. 

something broken in platformio's ESP8266 toolchain caused the `USE_SPIFFS` definition to get silently dropped from the SPIFFS build targets. [`612e5e4`](https://github.com/floatplane/MitsuQTT/pull/72/commits/612e5e4d4aed1e5997b20145a96b8c152bd25bc0) was needed to get this working correctly, which doesn't really make sense but 🤷 

https://github.com/floatplane/MitsuQTT/blob/612e5e4d4aed1e5997b20145a96b8c152bd25bc0/platformio.ini#L102-L103

**Comment by floatplane** [comment]
have verified that OTA updates work as expected for both LittleFS and SPIFFS builds on Wemos, so I think this is now good to go. this was more of a journey than I expected!

**Comment by Allram** [comment]
Works perfect, amazing job you did here 👌

**Pull request merged**
